[package]
name = "font-kit"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]

[features]
loader-freetype = ["freetype"]
loader-freetype-default = ["loader-freetype"]
source-fontconfig = ["servo-fontconfig"]
source-fontconfig-default = ["source-fontconfig"]

[dependencies]
arrayvec = "0.4"
bitflags = "1.0"
byteorder = "1.2"
dirs = "1.0"
euclid = "0.17"
failure = "0.1"
float-ord = "0.2"
itertools = "0.7"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
lyon_path = "0.10"
memmap = "0.6"
walkdir = "2.1"

[dependencies.freetype]
git = "https://github.com/servo/rust-freetype"
optional = true

[dependencies.servo-fontconfig]
version = "0.4"
optional = true

[dev-dependencies]
clap = "2.32"
colored = "1.6"
pbr = "1.0"
prettytable-rs = "0.7"

[target.'cfg(target_family = "windows")'.dependencies.winapi]
version = "0.3"
features = ["minwindef", "winbase"]

[target.'cfg(target_family = "windows")'.dependencies.dwrote]
git = "https://github.com/pcwalton/dwrote-rs"
branch = "additions"

[target.'cfg(target_os = "macos")'.dependencies.cocoa]
git = "https://github.com/servo/core-foundation-rs"

[target.'cfg(target_os = "macos")'.dependencies.core-foundation]
git = "https://github.com/servo/core-foundation-rs"

[target.'cfg(target_os = "macos")'.dependencies.core-graphics]
git = "https://github.com/servo/core-foundation-rs"

[target.'cfg(target_os = "macos")'.dependencies.core-text]
git = "https://github.com/servo/core-foundation-rs"

[target.'cfg(not(any(target_family = "windows", target_os = "macos")))'.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.'cfg(not(any(target_family = "windows", target_os = "macos")))'.dependencies.servo-fontconfig]
version = "0.4"
